# Generated by Django 4.2.2 on 2023-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_history_comments_bids_user_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
