# Generated by Django 4.2.2 on 2023-07-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='listing',
            field=models.CharField(max_length=64),
        ),
    ]
