# Generated by Django 4.2.2 on 2023-10-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_history_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='static/auctions/noImage.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='listings',
            name='image_url',
            field=models.URLField(default='static/auctions/noImage.png'),
        ),
    ]
