# Generated by Django 4.2.2 on 2023-10-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_image_listings_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='listing_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
