# Generated by Django 4.2.2 on 2023-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_history_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
    ]
