# Generated by Django 5.2.7 on 2025-10-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_history_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='defaults/noImage.png', upload_to='listings_images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, default='https://example.com/default-avatar.png', null=True),
        ),
    ]
