# Generated by Django 5.2.7 on 2025-10-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listings_image_alter_listings_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='listings_images/noImage.jpg', upload_to='listings_images/'),
        ),
    ]
